# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('plazo_dias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Plazo en dias')),
            ],
            options={
                'verbose_name': 'etapa',
                'verbose_name_plural': 'etapas',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'proceso',
                'verbose_name_plural': 'procesos',
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('plazo_dias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Plazo en dias')),
                ('tipo', models.CharField(choices=[('NORMAL', 'Requisito normal'), ('TEMPORIZADOR', 'Requisito temporizador')], default='NORMAL', max_length=15, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='RequisitoResultado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True)),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proceso.Requisito')),
            ],
            options={
                'verbose_name': 'RequisitoResultado',
                'verbose_name_plural': 'RequisitoResultados',
                'ordering': ('requisito',),
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
            },
        ),
        migrations.CreateModel(
            name='RolProceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('alias', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alias')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolproceso', to='proceso.Proceso', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Rol de Proceso',
                'verbose_name_plural': 'Roles de Proceso',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('plazo_dias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Plazo en dias')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea', to='proceso.Etapa', verbose_name='Etapa')),
                ('req_res_activador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='proceso.RequisitoResultado', verbose_name='Requisito resultado activador')),
                ('req_res_desactivador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='proceso.RequisitoResultado', verbose_name='Requisito resultado desactivador')),
                ('rol_ejecuta', models.ManyToManyField(to='proceso.RolProceso')),
                ('siguiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anterior', to='proceso.Tarea', verbose_name='Siguiente')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.AddField(
            model_name='requisitoresultado',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proceso.Resultado'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapa', to='proceso.Proceso', verbose_name='Proceso'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='siguiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anteriores', to='proceso.Etapa', verbose_name='Siguiente'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='tarea_activador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapa_activador', to='proceso.Tarea', verbose_name='Tarea activador'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='tarea_desactivador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapa_desactivador', to='proceso.Tarea', verbose_name='Tarea desactivador'),
        ),
    ]
