# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='siguiente',
        ),
        migrations.AddField(
            model_name='etapa',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siguientes', to='proceso.Etapa', verbose_name='Siguiente'),
        ),
    ]
