# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0002_auto_20171013_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siguientes', to='proceso.Etapa', verbose_name='Anterior'),
        ),
    ]
