# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0003_auto_20171210_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='orden',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='requisitoresultado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='requisitoresultado',
            name='requisito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proceso.Requisito', verbose_name='Requisito'),
        ),
        migrations.AlterField(
            model_name='requisitoresultado',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proceso.Resultado', verbose_name='Resultado'),
        ),
    ]
