# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0004_auto_20171227_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='siguiente',
        ),
        migrations.AddField(
            model_name='tarea',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siguiente', to='proceso.Tarea', verbose_name='Anterior'),
        ),
    ]
