# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0005_auto_20171228_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='orden',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
    ]
