# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0006_tarea_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('tipo', models.CharField(choices=[('INPUT', 'Input'), ('TEXTAREA', 'Textarea'), ('PASSWORD', 'Password'), ('NUMBER', 'Number'), ('EMAIL', 'Email'), ('CHECKBOX', 'Checkbox'), ('RADIOBUTTON', 'Radio-button'), ('SELECT', 'Select'), ('BUTTON', 'Button'), ('SLIDER', 'Slider'), ('FILEINPUT', 'File-input'), ('SLIDETOGGLE', 'Slide-toggle'), ('DATE', 'Date'), ('DATETIMELOCAL', 'Date-time-local'), ('MONTH', 'Month'), ('TIME', 'Time'), ('URL', 'Url')], default='INPUT', max_length=15, verbose_name='Tipo')),
                ('requerido', models.BooleanField(default=False, verbose_name='Requerido')),
                ('flex', models.IntegerField(blank=True, default=100, null=True, verbose_name='Flex')),
                ('minimo', models.IntegerField(blank=True, null=True, verbose_name='Minimo')),
                ('maximo', models.IntegerField(blank=True, null=True, verbose_name='Maximo')),
                ('backgroud', models.CharField(blank=True, max_length=300, null=True, verbose_name='Backgroud')),
                ('modelo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modelo')),
                ('json', models.TextField(blank=True, null=True, verbose_name='Json')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('prefix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prefix')),
                ('hint_start', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hint_start')),
                ('hint_end_count_text', models.BooleanField(default=False, verbose_name='Hint_end_count_text')),
                ('disabled', models.BooleanField(default=False, verbose_name='Disabled')),
                ('multiselect', models.NullBooleanField(default=False, verbose_name='Multiselect')),
            ],
            options={
                'verbose_name': 'campo',
                'verbose_name_plural': 'campo',
            },
        ),
        migrations.CreateModel(
            name='CampoValor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('valorFileInput', models.FileField(blank=True, null=True, upload_to='proceso/valor-file-inputs/', verbose_name='ValorFileInput')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campovalor', to='proceso.Campo', verbose_name='Campo')),
            ],
            options={
                'verbose_name': 'campoValor',
                'verbose_name_plural': 'campoValors',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario', to='proceso.Tarea', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'formulario',
                'verbose_name_plural': 'formularios',
            },
        ),
        migrations.AddField(
            model_name='campo',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campo', to='proceso.Formulario', verbose_name='Formulario'),
        ),
    ]
