# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0007_auto_20180104_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campovalor',
            name='campo',
        ),
        migrations.DeleteModel(
            name='CampoValor',
        ),
    ]
