# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0012_auto_20180201_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='proceso.Formulario', verbose_name='Formulario'),
        ),
    ]
