# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0016_auto_20180202_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='type',
            field=models.CharField(choices=[('input', 'Input'), ('textarea', 'Textarea'), ('password', 'Password'), ('number', 'Number'), ('email', 'Email'), ('checkbox', 'Checkbox'), ('radiobutton', 'Radio-button'), ('select', 'Select'), ('button', 'Button'), ('slider', 'Slider'), ('fileinput', 'File-input'), ('slidetoggle', 'Slide-toggle'), ('date', 'Date'), ('datetimelocal', 'Date-time-local'), ('month', 'Month'), ('time', 'Time'), ('url', 'Url')], default='input', max_length=15, verbose_name='Type'),
        ),
    ]
