# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0017_auto_20180203_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='flex',
        ),
        migrations.AddField(
            model_name='campo',
            name='width',
            field=models.IntegerField(blank=True, default=100, help_text='width in %', null=True, verbose_name='Width'),
        ),
    ]
