# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0020_auto_20180208_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='validation',
            field=models.ManyToManyField(through='proceso.CampoValidation', to='proceso.Validation'),
        ),
    ]
