# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0021_campo_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='tarea',
            field=models.ManyToManyField(to='proceso.Tarea'),
        ),
    ]
