# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0022_requisito_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='accept_fileinput',
            field=models.CharField(blank=True, help_text='Extención de los archivos que se puede adjuntar', max_length=500, null=True, verbose_name='Aceept for Fileinput'),
        ),
        migrations.AddField(
            model_name='campo',
            name='multiple_fileinput',
            field=models.BooleanField(default=False, help_text='Si el File input es para multiples Erchivos', verbose_name='Multiple'),
        ),
    ]
