# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-27 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0023_auto_20180605_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='model',
        ),
        migrations.AddField(
            model_name='campo',
            name='model_label',
            field=models.CharField(blank=True, help_text='Solo para selects', max_length=200, null=True, verbose_name='Model_label'),
        ),
        migrations.AddField(
            model_name='campo',
            name='model_name',
            field=models.CharField(blank=True, help_text='Solo para selects', max_length=200, null=True, verbose_name='Model_name'),
        ),
        migrations.AddField(
            model_name='campo',
            name='model_pk',
            field=models.CharField(blank=True, help_text='Solo para selects', max_length=200, null=True, verbose_name='Model_pk'),
        ),
    ]
