# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0025_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='roles_validadores',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Roles_validadores'),
        ),
        migrations.AddField(
            model_name='campo',
            name='tipo_validador',
            field=models.CharField(blank=True, choices=[('G', 'Grupal'), ('R', 'Rol'), ('P', 'Personal')], max_length=15, null=True, verbose_name='Tipo_validador'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='type',
            field=models.CharField(choices=[('input', 'Input'), ('textarea', 'Textarea'), ('password', 'Password'), ('number', 'Number'), ('email', 'Email'), ('checkbox', 'Checkbox'), ('radiobutton', 'Radio-button'), ('select', 'Select'), ('button', 'Button'), ('slider', 'Slider'), ('fileinput', 'File-input'), ('slidetoggle', 'Slide-toggle'), ('date', 'Date'), ('datetimelocal', 'Date-time-local'), ('month', 'Month'), ('time', 'Time'), ('url', 'Url'), ('validador', 'Validador'), ('generar_documentos', 'Generar-documentos')], default='input', max_length=15, verbose_name='Type'),
        ),
    ]
