# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-15 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0026_auto_20180806_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='campos_validados',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Campos_validados'),
        ),
        migrations.AddField(
            model_name='campo',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='proceso.Documento', verbose_name='Documento'),
        ),
    ]
