# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('config', '0001_initial'),
        ('tesis_proceso', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='config.Persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
            },
        ),
        migrations.CreateModel(
            name='Dictaminador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='config.Persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Dictaminador',
                'verbose_name_plural': 'Dictaminadores',
            },
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='config.Persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Jurado',
                'verbose_name_plural': 'Jurados',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('resumen', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('archivo', models.FileField(default='proyecto/archivos/none/default.pdf', upload_to='proyecto/archivos/', verbose_name='Archivo')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('estado', models.CharField(choices=[('PROCESO', 'En proceso'), ('TERMINADO', 'Terminado'), ('PUBLICADO', 'Publicado'), ('ABANDONADO', 'Abandonado'), ('OTRO', 'Otro')], default='PROCESO', max_length=15, verbose_name='Estado')),
                ('fecha_sustentacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de sustentación')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProyectoAsesor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(choices=[('ASESOR', 'Asesor principal'), ('COASESOR', 'Coasesor'), ('ASESOR1', 'Asesor 1'), ('ASESOR2', 'Asesor 2')], default='ASESOR', max_length=15, verbose_name='Tipo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Asesor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
            options={
                'verbose_name': 'ProyectoAsesor',
                'verbose_name_plural': 'ProyectoAsesores',
            },
        ),
        migrations.CreateModel(
            name='ProyectoDictaminador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(choices=[('PROYECTO', 'Proyecto de tesis'), ('INFORME', 'Informe de tesis')], default='PROYECTO', max_length=15, verbose_name='Etapa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('dictaminador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Dictaminador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
            options={
                'verbose_name': 'ProyectoDictaminador',
                'verbose_name_plural': 'ProyectoDictaminadors',
            },
        ),
        migrations.CreateModel(
            name='ProyectoJurado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('SECRETARIO', 'Secretario'), ('OTRO', 'Otro')], default='PRESIDENTE', max_length=15, verbose_name='Etapa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Jurado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
            options={
                'verbose_name': 'ProyectoJurado',
                'verbose_name_plural': 'ProyectoJurados',
            },
        ),
        migrations.CreateModel(
            name='Tesista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='config.Persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Tesista',
                'verbose_name_plural': 'Tesistas',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='asesor',
            field=models.ManyToManyField(through='proyecto.ProyectoAsesor', to='proyecto.Asesor'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='dictaminador',
            field=models.ManyToManyField(through='proyecto.ProyectoDictaminador', to='proyecto.Dictaminador'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='jurado',
            field=models.ManyToManyField(through='proyecto.ProyectoJurado', to='proyecto.Jurado'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='linea_investigacion',
            field=models.ManyToManyField(to='academico.LineaInvestigacion'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='proceso',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='tesis_proceso.TesisProceso', verbose_name='Proceso'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tesista',
            field=models.ManyToManyField(to='proyecto.Tesista'),
        ),
    ]
