# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='proceso',
            new_name='tesis_proceso',
        ),
    ]
