# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20171210_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='archivo',
            field=models.FileField(blank=True, default='proyecto/archivos/none/default.pdf', null=True, upload_to='proyecto/archivos/', verbose_name='Archivo'),
        ),
    ]
