# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20180202_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tesis_proceso',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='tesis_proceso.TesisProceso', verbose_name='Tesis_proceso'),
        ),
    ]
