# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-18 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20180203_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='linea_investigacion',
            field=models.ManyToManyField(blank=True, to='academico.LineaInvestigacion'),
        ),
    ]
