# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-13 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default='personas/fotos/none/default.png', upload_to='personas/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Género'),
        ),
    ]
