# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineainvestigacion',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineainvestigacion', to='academico.Escuela', verbose_name='Escuela'),
        ),
    ]
