# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20171222_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='academico.Facultad', verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='lineainvestigacion',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineainvestigacions', to='academico.Escuela', verbose_name='Escuela'),
        ),
    ]
